### ISSUE TITLE
Error when saving dynamic_file

### ISSUE THREAD

**Issue by Gabrielsvc** [dongqi-DQ/WRF4PALM#12]
> Resolving surface NaNs...                               
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:38<00:00,  7.76s/it]                                                                           
Writing NetCDF file                                     
Traceback (most recent call last):                      
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info                                                                              
    file = self._cache[self._key]                       
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__                                                                                               
    value = self._cache[key]                            
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/isi-user/Repos/WRF4PALM/dynamic_files/rn_atlas_dynamic_2017_1_1_1',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

> During handling of the above exception, another exception occurred:                                             

>Traceback (most recent call last):                      
  File "/home/isi-user/Repos/WRF4PALM/run_config_wrf4palm.py", line 590, in <module>                                                                                                                                             
    nc_output.to_netcdf(nc_output_name)                                                                         
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/core/dataset.py", line 1900, in to_netcdf                                                                                                     
    return to_netcdf(                                   
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/api.py", line 1060, in to_netcdf                                                                                                     
    store = store_open(target, mode, format, group, **kwargs)                                                   
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 380, in open                                                                                                      
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)                                                                                                                                                  
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 328, in __init__                                                                                                  
    self.format = self.ds.data_model                    
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 389, in ds                                                                                                        
    return self._acquire()                              
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 383, in _acquire                                                                                                  
    with self._manager.acquire_context(needs_lock) as root:                                                     
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/contextlib.py", line 119, in __enter__                                                                                                                             
    return next(self.gen)                               
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context                                                                                       
    file, cached = self._acquire_with_cache_info(needs_lock)                                                    
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info                                                                              
    file = self._opener(*self._args, **kwargs)                                                                  
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__                                                                                                                                               
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success                                                                                                                                             
PermissionError: [Errno 13] Permission denied: b'/home/isi-user/Repos/WRF4PALM/dynamic_files/rn_atlas_dynamic_2017_1_1_1'  

Last one! In this case the dynamic file wasn't being created due to the folder `dynamic_files` not existing, similar to issue [10](https://github.com/dongqi-DQ/WRF4PALM/issues/10). In the same way, this can be solved by adding the folder or adding a verification step and creating the folder at this step.

Cheers!

**Comment by dongqi-DQ** [comment]
Thank you @Gabrielsvc. Similar to issue #10, a fix has been applied. I'll close this issue now.
