### ISSUE TITLE
About chem to palm

### ISSUE THREAD

**Issue by Solaydh** [dongqi-DQ/WRF4PALM#29]
Dear Prof Lin,

I‘m sorry to bother you with a few questions:

      (1) Dealing with initial conditions of chemistry through adding variables in this scripts can be used as a simple method?  Just like : "for varbc in ["QVAPOR","pt"]"  ----> "for varbc in ["QVAPOR","pt","PM10", "NOx" ,"SO4".......]"
     
      (2) Unlike the variable of (u,v,w,pt,qvapor) , the boundary conditions of chem-variables are not given in the list from "https://palm.muk.uni-hannover.de/trac/wiki/doc/app/iofiles/pids/dynamic", and there are only the initial conditions (such as init_atmosphere_pm10、no2...... ). 
           Therefore,  the "Is_force_pm10, no2......" should be needed? puzzled......

        Thanks for your time! 

Sincerely,

**Comment by dongqi-DQ** [comment]
Hi there, 

Sorry, I've been on vacation, and I'm a bit slow catching up with my emails these days.

It seems that your questions are related to the chemistry module in PALM. Unfortunately, these features are not supported in WRF4PALM yet. I have very limited knowledge regarding the chemistry module, so I couldn't help you much here. I will have a look later this month, but for the second question, it might be easier to ask the PALM developers (i.e. open a ticket on the PALM website). 

I will mark this issue as "to do" for now.

Thanks,
Dongqi

**Comment by aqianxiangkail** [comment]
Hi, dear friends,
have you successfully done the chemical dynamic driver for palm model? How do you do that, using WRF_Interface in https://palm.muk.uni-hannover.de/trac/wiki/doc/app/iofiles/wrf_interface or another simple and detailed way to handle the CAMX files for the chemical initial and boundary conditions?

Thank you for your help.

Besti

**Comment by Solaydh** [comment]
> Hi, dear friends, have you successfully done the chemical dynamic driver for palm model? How do you do that, using WRF_Interface in https://palm.muk.uni-hannover.de/trac/wiki/doc/app/iofiles/wrf_interface or another simple and detailed way to handle the CAMX files for the chemical initial and boundary conditions?
> 
> Thank you for your help.
> 
> Besti

Hi, dear friends, 
Previous ideas mainly focused on the WRF-chem because we are unskilled for CAMx. Directly, adding variables (source from wrfout) may be recognized as a method with simple modifications, and you can imitate other variables (such as w,pt,qvapor) in Lin' s scripts, just like starting with "o3_wrf = ds_interp.o3[:,0,:,:].load()", imitating "qv2_wrf = ds_interp.Q2.load()" given in scripts. 

However, the validation (running and evaluating) was set aside due to other projects, and these were only the initial ideas. Thanks for your further exploring!

Sincerely,

**Comment by aqianxiangkail** [comment]
> > Hi, dear friends, have you successfully done the chemical dynamic driver for palm model? How do you do that, using WRF_Interface in https://palm.muk.uni-hannover.de/trac/wiki/doc/app/iofiles/wrf_interface or another simple and detailed way to handle the CAMX files for the chemical initial and boundary conditions?
> > Thank you for your help.
> > Besti
> 
> Hi, dear friends, Previous ideas mainly focused on the WRF-chem because we are unskilled for CAMx. Directly, adding variables (source from wrfout) may be recognized as a method with simple modifications, and you can imitate other variables (such as w,pt,qvapor) in Lin' s scripts, just like starting with "o3_wrf = ds_interp.o3[:,0,:,:].load()", imitating "qv2_wrf = ds_interp.Q2.load()" given in scripts.
> 
> However, the validation (running and evaluating) was set aside due to other projects, and these were only the initial ideas. Thanks for your further exploring!
> 
> Sincerely,

dear friends
thank you for your ideas. Have you any one configured python templates can be shared for generating dynamic driver based on Wrf-Chem (any one of air components)? It is better  to do it using reference.....

Thanks so much for your help.

Besti,

**Comment by aqianxiangkail** [comment]
> > Hi, dear friends, have you successfully done the chemical dynamic driver for palm model? How do you do that, using WRF_Interface in https://palm.muk.uni-hannover.de/trac/wiki/doc/app/iofiles/wrf_interface or another simple and detailed way to handle the CAMX files for the chemical initial and boundary conditions?
> > Thank you for your help.
> > Besti
> 
> Hi, dear friends, Previous ideas mainly focused on the WRF-chem because we are unskilled for CAMx. Directly, adding variables (source from wrfout) may be recognized as a method with simple modifications, and you can imitate other variables (such as w,pt,qvapor) in Lin' s scripts, just like starting with "o3_wrf = ds_interp.o3[:,0,:,:].load()", imitating "qv2_wrf = ds_interp.Q2.load()" given in scripts.
> 
> However, the validation (running and evaluating) was set aside due to other projects, and these were only the initial ideas. Thanks for your further exploring!
> 
> Sincerely,

Dear friends,
I have imitated these commands like QVAPOR to set the dynamic parameters, but it also occurs a problem in the last section about writing into NC file. 

Traceback (most recent call last):
  File "/home/qian/WRF4PALM_v1.1.2/run_config_wrf4palm_chem.py", line 847, in <module>
    nc_output['ls_forcing_top_pm10'] = xr.DataArray(pm10_top[:,:,:],dims=['time', 'y', 'x'],
  File "/home/qian/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/core/dataarray.py", line 750, in __getitem__
    return self.isel(indexers=self._item_key_to_dict(key))
  File "/home/qian/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/core/dataarray.py", line 714, in _item_key_to_dict
    key = indexing.expanded_indexer(key, self.ndim)
  File "/home/qian/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/xarray/core/indexing.py", line 46, in expanded_indexer
    raise IndexError("too many indices")
IndexError: too many indices

Do you also experience this error? Maybe give me some ideas?
Thanks for your help.

Besti,
 Qian
