### ISSUE TITLE
lock error 

### ISSUE THREAD

**Issue by aqianxiangkail** [dongqi-DQ/WRF4PALM#34]
Dear Prof. Lin,
I am a newcomer, I have been stuck for a few days about the incompatibility between the xarray and salem (all the new versions) when reading WRF files. Could you help me? Thanks a lot.

Reading WRF
Traceback (most recent call last):
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/salem/sio.py", line 1180, in open_mf_wrf_dataset
    datasets = [open_wrf_dataset(p, chunks=chunks or {}, lock=lock)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/salem/sio.py", line 987, in open_wrf_dataset
    ds = xr.open_dataset(NetCDF4DataStore(nc), **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/xarray/backends/api.py", line 541, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
TypeError: StoreBackendEntrypoint.open_dataset() got an unexpected keyword argument 'lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/dsshome1/09/ge89may2/WRF4PALM/run_config_wrf4palm.py", line 139, in <module>
    with salem.open_mf_wrf_dataset(wrf_files) as ds_raw:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/salem/sio.py", line 1186, in open_mf_wrf_dataset
    datasets = [open_wrf_dataset(p, chunks=chunks or {}) for p in paths]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/salem/sio.py", line 1016, in open_wrf_dataset
    ds['west_east'] = ds.salem.grid.x_coord
                      ^^^^^^^^
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/xarray/core/extensions.py", line 38, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "/dss/dsshome1/09/ge89may2/miniconda3/envs/myenv_geotiff/lib/python3.12/site-packages/salem/sio.py", line 427, in __init__
    raise RuntimeError('dataset Grid not understood.')
RuntimeError: dataset Grid not understood.

**Comment by dongqi-DQ** [comment]
It looks like you are using Python3.12. The original code of WRF4PALM was written in an earlier version of Python. 

Can you please refer to the yml file in the repo for more details regarding the package versions? [wrf4palm_env.yml](https://github.com/dongqi-DQ/WRF4PALM/blob/v1.1.2/wrf4palm_env.yml)
In the yml file we have 
python=3.9.7
salem=0.3.5
xarray=0.19.0

If you are using a Linux machine, you can also try to create a new python environment from the yml file. See conda website for more details https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by aqianxiangkail** [comment]
thank you very much  for your so quick reply
