### ISSUE TITLE
ValueError: new dimensions ('time', 'y', 'x') must be a superset of existing dimensions ('time', 'south_north', 'west_east')

### ISSUE THREAD

**Issue by xanfus** [dongqi-DQ/WRF4PALM#37]
```
Reading WRF
/home/alpha/pythonenvs/palm/lib/python3.11/site-packages/xarray/core/indexing.py:1430: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  return self.array[key]
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:220: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  nx_wrf, ny_wrf = ds_wrf.dims['west_east'], ds_wrf.dims['south_north']
cfg file is saved: lsf256a_wrfout_d02_2023-08-15_180000_nested
Start horizontal interpolation
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:298: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_interp = ds_interp.drop(["west_east", "south_north"]
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:302: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_interp_u = ds_interp_u.drop(["west_east", "south_north"]
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:306: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_interp_v = ds_interp_v.drop(["west_east", "south_north"]
Calculating soil temperature and moisture from WRF
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [00:06<00:00, 18.87it/s]
Start vertical interpolation
create empty datasets
create empty datasets for staggered U and V (west&east boundaries)
create empty datasets for staggered U and V (south&north boundaries)
remove unused vars from datasets
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:382: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_we = ds_we.drop(var)
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:383: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_sn = ds_sn.drop(var)
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:385: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_we_ustag = ds_we_ustag.drop(var)
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:386: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_sn_ustag = ds_sn_ustag.drop(var)
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:388: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_we_vstag = ds_we_vstag.drop(var)
/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py:389: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
  ds_sn_vstag = ds_sn_vstag.drop(var)
load dataset for west&east boundaries
load dataset for south&north boundaries
load dataset for west&east boundaries (staggered U)
load dataset for south&north boundaries (staggered U)
load dataset for west&east boundaries (staggered V)
load dataset for south&north boundaries (staggered V)
create datasets to save data in PALM coordinates
create zeros arrays for vertical interpolation
Processing QVAPOR for west and east boundaries
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 96/96 [00:15<00:00,  6.13it/s]
Traceback (most recent call last):
  File "/home/alpha/modeling/lsf256/../../WRF4PALM/run_config_wrf4palm.py", line 422, in <module>
    ds_palm_we[varbc] = multi_zinterp(max_pool, ds_we, varbc, z, ds_palm_we)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alpha/WRF4PALM/dynamic_util/process_wrf.py", line 25, in multi_zinterp
    ds_out[var].loc[dict(z=lvl)] = pool_dict[lvl] 
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/alpha/pythonenvs/palm/lib/python3.11/site-packages/xarray/core/dataarray.py", line 236, in __setitem__
    self.data_array[dim_indexers] = value
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/alpha/pythonenvs/palm/lib/python3.11/site-packages/xarray/core/dataarray.py", line 878, in __setitem__
    self.variable[key] = value
    ~~~~~~~~~~~~~^^^^^
  File "/home/alpha/pythonenvs/palm/lib/python3.11/site-packages/xarray/core/variable.py", line 833, in __setitem__
    value = value.set_dims(dims).data
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/alpha/pythonenvs/palm/lib/python3.11/site-packages/xarray/core/variable.py", line 1323, in set_dims
    raise ValueError(
ValueError: new dimensions ('time', 'y', 'x') must be a superset of existing dimensions ('time', 'south_north', 'west_east')

```

**Comment by xanfus** [comment]
Currently testing in wrf4palm environment...
Works.

**Comment by patikit** [comment]
@xanfus Hello, I have the same problem. How did you solve the problem, what do you mean with testing in wrf4palm enviorment. Because I am processing it in the wrf4palm environment and it does not work for me.
Kind regards and thank you in advance!
